region         = "us-west-2"
ami_id         = "ami-0e1d35993cb249cee"  # Amazon Linux 2 (us-west-2)
instance_type  = "t3.micro"              # autorisé dans le sandbox
vpc_cidr      = "10.0.0.0/16"
subnet_cidr   = "10.0.1.0/24"
instance_type = "t3.micro"
key_name      = "lab-key"       # Nom de ta clé SSH créée dans le sandbox
db_user       = "admin"
db_pass       = "Password123!"
